// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekckskdowznllcqwwirt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrY2tza2Rvd3pubGxjcXd3aXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODQ5MjcsImV4cCI6MjA2MjA2MDkyN30.JlFAzHhw9KFKfMEclEatQ34oconzdDYkJ8kWhGhO2SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);